//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int Company_Id { get; set; }
        public string AspNetRole_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Detail { get; set; }
        public string Url { get; set; }
        public bool IsRead { get; set; }
        public bool IsAlertShow { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual User User { get; set; }
    }
}
