//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProduct
    {
        public int Id { get; set; }
        public int Sale_Id { get; set; }
        public int ProductStock_Id { get; set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
        public double SalePrice { get; set; }
        public double Discount { get; set; }
        public double DiscountedPrice { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ProductStock ProductStock { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
