//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int RecordId { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public string Detail { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
